### ISSUE TITLE
Option to "bundle exec" jekyll

### ISSUE THREAD

**Issue by rdricco** [ixkaito/frasco#18]
I couldn't execute the gulp task without the bundle exec before jekyll command. To work I needed to change lines 75 and 168 on your gulpfile.js:

**before**:
`return cp.spawn(jekyll, ['build', '--config', jekyllConfig], {stdio: 'inherit', env: process.env})`
**after**:
` return cp.exec('bundle', ['exec', 'jekyll', '--config', jekyllConfig], {stdio: 'inherit', env: process.env})`

**Comment by ixkaito** [comment]
@rdricco 

Thank you for your report. I'll test for this.

**Comment by rdricco** [comment]
It is not necessary, I found we can run `bundle exec npm start`. This command works fine, even the config.yml can be edited (except the gems) without the need of reload the script.
I think could be a good idea to mention this command on instructions page.

**Comment by ixkaito** [comment]
@rdricco Thanks for your information! I didn't notice `bundle exec npm start` works. I'll add this to the documentation :)
