### ISSUE TITLE
Why using Webpack & Gulp

### ISSUE THREAD

**Issue by atais** [ixkaito/frasco#22]
Hi! 
I have just started working on this project and it looks really promising.

One thing I can not understand though is, why are you running webpack from gulp? Why not just stick to webpack?

**Comment by ixkaito** [comment]
@atais Thanks!

> One thing I can not understand though is, why are you running webpack from gulp? Why not just stick to webpack?

First, I don't like importing CSS in JS files.
Second, to make this project be able to run from Jekyll without npm/gulp/webpack.
Third, to integrate the configuration.
