### ISSUE TITLE
Need option to switch between JS-Concat or Webpack

### ISSUE THREAD

**Issue by boxdox** [ixkaito/frasco#25]
I don't know why, but webpack doesn't seem to work for me. How can I use gulp-concat and gulp-uglify, instead of webpack.
Instead, I want to just concat and uglify JS.
Also, please add an option for UnCSS and UnJS.

**Comment by ixkaito** [comment]
I'll make some enhancement.

**Comment by ixkaito** [comment]
@boxdox Released v1.0.0 and removed gulp. Now Frasco uses npm-scripts to run tasks. Please have a try.
