### ISSUE TITLE
Remove gulp-uglify

### ISSUE THREAD

**Issue by ixkaito** [ixkaito/frasco#34]
webpack v4+ will minify your code by default in production mode.

**Comment by Nsokyi** [comment]
Is there way to get webpack not to neaten up my js until it's in production mode/build?

**Comment by edheltzel** [comment]
@Nsokyi  Inside of the `frasco.config.js` you can set the `tasks` for `webpack` to `false`.

```js
  tasks: {
    browsersync: true,
    eslint:      true,
    imagemin:    true,
    sass:        true,
    watch:       true,
    webpack:     false,
  },
```

**Comment by Nsokyi** [comment]
Thanks, I tried that and oddly enough it doesn't have any effect?

**Comment by ixkaito** [comment]
@Nsokyi If you set `webpack` to `false`, webpack will not do anything, so you have to directly edit your js files in the `assets/js` folder. **Note: if you reset `webpack` to `true`, your js files in `assets/js` will be overwritten by files with the same name in `assets/_js`.**

I'm sorry that for now, there's no way to switch minification between development and production.

**Comment by Nsokyi** [comment]
OK, thanks for getting back to me.

**Comment by ixkaito** [comment]
@Nsokyi On the [latest release](https://github.com/ixkaito/frasco/releases/tag/v0.8.5), I removed `gulp-uglify` because Webpack automaticlly compress js files. For now, you can add a Webpack configuration `devtool: 'source-map'` to [frasco.config.js](https://github.com/ixkaito/frasco/blob/master/frasco.config.js) to enable source maps. This might make your debug easier.

```
  webpack: {
    mode:   'production',
    devtool: 'source-map',
    module: {
      rules: [],
    },
  },
```
