### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by Nsokyi** [ixkaito/frasco#38]
I get the following when I try to run npm start

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.7
3 info using node@v13.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle frasco@0.8.8~prestart: frasco@0.8.8
6 info lifecycle frasco@0.8.8~start: frasco@0.8.8
7 verbose lifecycle frasco@0.8.8~start: unsafe-perm in lifecycle true
8 verbose lifecycle frasco@0.8.8~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/noahbreen/Sites/Jekyll/portfolio__001/frasco/node_modules/.bin:/Users/noahbreen/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle frasco@0.8.8~start: CWD: /Users/noahbreen/Sites/Jekyll/portfolio__001/frasco
10 silly lifecycle frasco@0.8.8~start: Args: [ '-c', 'bundle exec gulp' ]
11 silly lifecycle frasco@0.8.8~start: Returned: code: 1  signal: null
12 info lifecycle frasco@0.8.8~start: Failed to exec start script
13 verbose stack Error: frasco@0.8.8 start: `bundle exec gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid frasco@0.8.8
15 verbose cwd /Users/noahbreen/Sites/Jekyll/portfolio__001/frasco
16 verbose Darwin 19.5.0
17 verbose argv "/usr/local/Cellar/node/13.8.0/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v13.8.0
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error frasco@0.8.8 start: `bundle exec gulp`
22 error Exit status 1
23 error Failed at the frasco@0.8.8 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by edheltzel** [comment]
@Nsokyi try changing your node version to 11 or below.

**Comment by Nsokyi** [comment]
Thanks for your reply, I tried that and got the following: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.7.0
3 info using node@v11.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle frasco@0.8.8~prestart: frasco@0.8.8
6 info lifecycle frasco@0.8.8~start: frasco@0.8.8
7 verbose lifecycle frasco@0.8.8~start: unsafe-perm in lifecycle true
8 verbose lifecycle frasco@0.8.8~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/noahbreen/Sites/Jekyll/portfolio__001/frasco/node_modules/.bin:/Users/noahbreen/.rvm/gems/ruby-2.7.0/bin:/Users/noahbreen/.rvm/gems/ruby-2.7.0@global/bin:/Users/noahbreen/.rvm/rubies/ruby-2.7.0/bin:/Users/noahbreen/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/noahbreen/.rvm/bin
9 verbose lifecycle frasco@0.8.8~start: CWD: /Users/noahbreen/Sites/Jekyll/portfolio__001/frasco
10 silly lifecycle frasco@0.8.8~start: Args: [ '-c', 'bundle exec gulp' ]
11 silly lifecycle frasco@0.8.8~start: Returned: code: 1  signal: null
12 info lifecycle frasco@0.8.8~start: Failed to exec start script
13 verbose stack Error: frasco@0.8.8 start: `bundle exec gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid frasco@0.8.8
15 verbose cwd /Users/noahbreen/Sites/Jekyll/portfolio__001/frasco
16 verbose Darwin 19.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v11.15.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error frasco@0.8.8 start: `bundle exec gulp`
22 error Exit status 1
23 error Failed at the frasco@0.8.8 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by edheltzel** [comment]
i generally remove the `nodes_module` folder and any lock files with a fresh `npm install`

**Comment by Nsokyi** [comment]
Sorry, probably a really dumb question but if you remove the nodes_module folder then doesn't that get rid of Gulp and other dependencies that help genarate the site?

**Comment by edheltzel** [comment]
yeah it will but once you re-run `npm install` all the dependencies will be re-installed.

**Comment by Nsokyi** [comment]
It's OK, I did a fresh Frasco install and moved all my bit's and bobs over successfully. Thanks for your help.

**Comment by edheltzel** [comment]
awesome and no problem.
