### ISSUE TITLE
Default config processing images into the wrong distribution folder

### ISSUE THREAD

**Issue by lmerriam** [ixkaito/frasco#44]
On a new repo with no changes to `package.json` or `imagemin.js` I am seeing files placed in `/assets/_src/images` going to `/assets/images/assets/_src/images`. SCSS and JS seem to be compiling to their proper distribution folders. Changing `config.image.dist` in `package.json` does not appear to have any effect on the final location of the image files.

**Comment by lmerriam** [comment]
I did run `NPM audit fix` after install but the only package it appears to have upgraded is BrowserSync according to the packages.json file

**Comment by ixkaito** [comment]
Hi @lmerriam, I couldn't see this bug. `npm run dev`, `npm run build` both minify images from `/assets/_src/images/` to `/assets/images/` and copy them to `/sites/assets/images`.

I also tested changing `$npm_package_config_image_dist` to `"assets/img"`. Files seem to be minified to the proper `/assets/img` folder and copied to `/sites/assets/img`.

Would you tell me your OS?
